---
title: 'Cyprus: COVID-19 Analysis'
author: "David Jackson"
Reported: "12/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,message = FALSE,warning = FALSE)
library(ggplot2)
library(scales)
library(RSQLite)
library(plotly)
library(dplyr)
library(forecast)
theme_set(theme_linedraw() + theme(panel.grid = element_line(linetype = 'dashed')))

```
```{r}
rm(list=ls())
source("../DATA/movavg.R")
db <- db <- dbConnect(RSQLite::SQLite(),dbname= "../COVIDDB/COVID.sqlite3")
df <- dbGetQuery(db,"select * from ECDC ")
df <- subset(df,Countries =="Cyprus"  )
df$Reported <- as.Date(df$Reported)
df <- df[order(df$Reported),]
df$CMA <- ma(df$Cases,7)
df$DMA <- ma(df$Deaths,7)
```

#### Daily COVID-19 Cases

```{r}
df %>% filter(Reported >="2020-02-27" & Cases >0) %>%
ggplot() + geom_line(aes(x=Reported,y=Cases)) +
  geom_smooth(aes(x=Reported,y=Cases),span=0.25) +
  labs(title="Sweden Daily Cases")

ggplot(df) + geom_line(aes(x=Reported,y=CMA),col="red") + 
  labs(title="Seven Day Moving Average: Cases")

```

#### Daily Deaths

```{r}
df %>% filter(Reported>="2020-03-20" & Deaths>0) %>%
ggplot() +  geom_line(aes(x=Reported,y=Deaths)) +
  geom_smooth(aes(x=Reported,y=Deaths),span=0.25) +
  labs(title="Sweden Daily Deaths") 

ggplot(df) + geom_line(aes(x=Reported,y=DMA),col="red") + 
  labs(title="Seven Day Moving Average: Deaths")
  
```

### df COVID19 Mortality Rate

```{r}
df$Rate <- df$Deaths/df$Cases 
df %>% filter(Reported >= "2020-03-01") %>%
ggplot() + geom_line(aes(x=Reported,y=Rate)) +
  scale_y_continuous(labels = scales::percent) +
  labs(title="COVID19 Mortality Rate ",x="Reported Reported",y="Mortality Rate") + geom_hline(yintercept = mean(na.omit(df$Rate)),col="red",lwd=1.5)

```

#### Non-Moving Average By Week and By Month

```{r}
df$Monthly <- as.Date(cut(df$Reported,
  breaks = "month"))
df$Weekly <- as.Date(cut(df$Reported,
  breaks = "week",
  start.on.monday = FALSE))

```
```{r}
Weekly_Cases <- aggregate(Cases~Weekly,df,FUN=sum)
Weekly_Deaths <- aggregate(Deaths~Weekly,df,FUN=sum)
Weekly_Cases$DRate <- Weekly_Deaths$Deaths/Weekly_Cases$Cases

```
```{r}
ggplot(Weekly_Cases) + geom_col(aes(x=Weekly,y=Cases)) + 
  labs(title="Weekly Cases",x="Reported Reported", y="Weekly Cases") +
  geom_hline(yintercept = mean(Weekly_Cases$Cases),col="red",lwd=1.5) +
  scale_y_continuous(labels = scales::comma) 


ggplot(Weekly_Deaths) + geom_col(aes(x=Weekly,y=Deaths)) + 
  labs(title="Weekly Deaths",x="Reported Reported", y="Weekly Deaths") +
  scale_y_continuous(labels = scales::comma) +
  geom_hline(yintercept = mean(Weekly_Deaths$Deaths),col="red",lwd=1.5)
``` 

#### Monthly Cases and Deaths

```{r}

Monthly_Cases <- aggregate(Cases~Monthly,df,FUN=sum)
Monthly_Deaths <- aggregate(Deaths~Monthly,df,FUN=sum)
Monthly_Cases$DRate <- Monthly_Deaths$Deaths/Monthly_Cases$Cases

```
```{r}
ggplot(Monthly_Cases) + geom_col(aes(x=Monthly,y=Cases)) +
  labs(title="Monthly Cases") +
  scale_y_continuous(labels = scales::comma)

ggplot(Monthly_Deaths) + geom_col(aes(x=Monthly,y=Deaths)) +
  labs(title="Monthly Deaths") +
  scale_y_continuous(labels = scales::comma)
```

